// ═══════════════════════════════════════════════════════════════
// INHIMALAYS — Data Layer (HIMACHAL PRADESH ONLY)
// Curated by locals from the hills of Himachal
// ═══════════════════════════════════════════════════════════════

const DESTINATIONS = [
  { id:'manali', image:'https://images.unsplash.com/photo-1626714486580-08709e99a341?q=80&w=1600&auto=format&fit=crop', name:'Manali', region:'Kullu Valley', icon:'🏔️', color:'#C8E600', difficulty:'Easy', altitude:'2,050m', temp:'-5°C to 30°C', tagline:'Gateway to Adventure', description:'Nestled in the Beas River valley at the northern end of Kullu Valley, Manali is the launching pad for Rohtang Pass, Solang Valley and Leh Highway. Ancient temples like Hadimba Devi and Manu Temple sit among deodar forests. Old Manali\'s cobbled lanes contrast with Mall Road\'s bustle.', bestMonths:[4,5,6,9,10,11,12], highlights:['Hadimba Devi Temple — 1553 wooden pagoda in a deodar grove','Solang Valley — skiing in winter, paragliding in summer','Old Manali — backpacker cafes and Manu Temple','Rohtang Pass — 3,978m gateway to Lahaul','Jogini Waterfall — gentle trek through apple orchards'], mustDo:['Drive the Atal Tunnel to Lahaul-Spiti','Eat trout at a riverside dhaba in Old Manali','Soak in Vashisht hot springs','Shop for Kullu shawls at Bhuttico'], budget:{backpacker:'₹800–1,200/day',mid:'₹2,500–4,500/day',luxury:'₹8,000–15,000/day'}, permits:'No special permits needed. Rohtang Pass requires ₹550 vehicle permit from DC Kullu (book at rohtangpermits.nic.in).', gettingThere:'Bhuntar Airport (50km), Volvo from Delhi ISBT (12hr), Chandigarh (8hr)', climate:{summer:'10–30°C, clear and ideal',winter:'-5 to 10°C, heavy snowfall Dec-Feb'}, tags:['adventure','backpacking','cafes','snow','trek'] },
  { id:'shimla', image:'https://images.unsplash.com/photo-1596522521191-44755106828f?q=80&w=1600&auto=format&fit=crop', name:'Shimla', region:'Shimla District', icon:'🏛️', color:'#5B9BD5', difficulty:'Easy', altitude:'2,200m', temp:'-2°C to 28°C', tagline:'Queen of Hills', description:'The former summer capital of British India, Shimla wraps around a ridge at 2,200m. The Mall Road, Christ Church (1857), and Viceregal Lodge showcase colonial grandeur. Beyond the obvious, discover Jakhu Temple\'s Hanuman statue, Chadwick Falls, and the narrow-gauge Kalka-Shimla Railway — a UNESCO World Heritage line.', bestMonths:[3,4,5,6,9,10,11,12], highlights:['The Ridge & Mall Road — pedestrian heart of the city','Christ Church — second oldest church in North India','Kalka-Shimla Railway — 102 tunnels, 800+ bridges','Jakhu Temple — 33m Hanuman statue at 2,455m','Kufri — mini ski resort 16km from Shimla'], mustDo:['Ride the toy train from Kalka to Shimla (5 hours)','Walk the heritage trail through the Old Town','Try Shimla mirch ki chutney at Baljees','Watch sunset from Scandal Point on the Ridge'], budget:{backpacker:'₹900–1,400/day',mid:'₹3,000–5,000/day',luxury:'₹6,000–12,000/day'}, permits:'None required.', gettingThere:'Shimla Airport Jubbarhatti (23km), Kalka Railway (96km), NH-5 from Chandigarh (4hr)', climate:{summer:'15–28°C, pleasant',winter:'-2 to 12°C, snowfall Dec-Feb'}, tags:['heritage','colonial','photography','cafes'] },
  { id:'spiti', image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1600&auto=format&fit=crop', name:'Spiti Valley', region:'Lahaul-Spiti', icon:'🏜️', color:'#E8764A', difficulty:'Moderate', altitude:'3,800m', temp:'-20°C to 25°C', tagline:'The Middle Land', description:'A cold desert valley at 3,800m between Tibet and India, Spiti is one of the least populated regions in the country. Ancient Buddhist monasteries — Ki, Tabo (1,000+ years old), Dhankar — perch on barren cliffs. The surreal moonscapes, fossil-rich Langza, and the frozen Spiti River define raw, high-altitude Himachal.', bestMonths:[6,7,8,9], highlights:['Ki Monastery — 1,000-year-old gompa at 4,166m','Tabo Monastery — "Ajanta of the Himalayas" founded 996 AD','Chandratal Lake — crescent moon lake at 4,300m','Langza — Buddha statue with Himalayan backdrop, marine fossils','Dhankar — fort-monastery on a crumbling cliff'], mustDo:['Drive Manali-Kaza via Kunzum Pass (4,551m)','Stargaze from Kibber (4,270m) — one of the highest villages','Visit the Tabo caves where monks meditated','Eat thukpa and momos at a Kaza roadside dhaba'], budget:{backpacker:'₹1,000–1,800/day',mid:'₹2,500–4,000/day',luxury:'₹5,000–8,000/day'}, permits:'Inner Line Permit required for areas near the Indo-Tibetan border (free, apply at DC Kaza or Reckong Peo).', gettingThere:'Kaza via Manali (12hr) or Shimla-Reckong Peo-Kaza (2 days). No airport. HRTC buses run seasonally.', climate:{summer:'5–25°C, dry and clear',winter:'-20 to -5°C, roads closed Nov-May'}, tags:['monasteries','photography','offbeat','adventure','tibetan'] },
  { id:'dharamshala', image:'https://images.unsplash.com/photo-1622308644420-a6e545dff66e?q=80&w=1600&auto=format&fit=crop', name:'Dharamshala', region:'Kangra Valley', icon:'🙏', color:'#FFD54F', difficulty:'Easy', altitude:'1,475m', temp:'0°C to 32°C', tagline:'Land of the Dalai Lama', description:'Divided into lower Dharamshala (1,475m) and upper McLeodGanj (1,770m), this is the seat of the Tibetan government-in-exile. The Dalai Lama\'s Tsuglagkhang Complex, Tibetan Museum, and Namgyal Monastery form the spiritual core. Bhagsu Waterfall, Dal Lake, and Dharamkot offer nature escapes above the Kangra Valley.', bestMonths:[3,4,5,6,9,10,11], highlights:['Tsuglagkhang Complex — Dalai Lama\'s temple','Bhagsu Waterfall & Bhagsunath Temple','St. John in the Wilderness Church (1852)','HPCA Cricket Stadium — most scenic ground in India','Namgyal Monastery — largest Tibetan monastery outside Tibet'], mustDo:['Attend a teaching by the Dalai Lama (check schedule)','Trek to Triund (2,875m) for Dhauladhar views','Eat Tibetan set lunch at Lung Ta Japanese Cafe','Shop for Tibetan handicrafts in McLeodGanj market'], budget:{backpacker:'₹700–1,100/day',mid:'₹2,000–3,500/day',luxury:'₹5,000–10,000/day'}, permits:'None required.', gettingThere:'Gaggal Airport (15km), bus from Delhi (10hr), Pathankot Railway (85km)', climate:{summer:'15–32°C, monsoon Jul-Sep',winter:'0–15°C, occasional snow in McLeodGanj'}, tags:['spiritual','tibetan','culture','trek','cafes'] },
  { id:'kasol', image:'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?q=80&w=1600&auto=format&fit=crop', name:'Kasol', region:'Parvati Valley', icon:'🌲', color:'#2D6A4F', difficulty:'Easy', altitude:'1,640m', temp:'0°C to 30°C', tagline:'Mini Israel of India', description:'A tiny hamlet on the banks of the Parvati River between Bhuntar and Manikaran. Kasol is the base camp for Kheerganga and the Parvati Valley circuit. Israeli cafes, trance music, and dense pine forests create a unique counter-culture vibe. Manikaran\'s hot springs and Gurudwara are a short drive away.', bestMonths:[3,4,5,6,9,10,11], highlights:['Parvati River — crystal clear rapids through pine forests','Manikaran — sacred hot springs and Gurudwara Sahib','Chalal village — 30-minute walk across the river','Tosh — hilltop village with panoramic valley views','Malana — ancient village with its own democratic system'], mustDo:['Trek to Kheerganga hot springs (12km one-way)','Eat Israeli shakshuka at Jim Morrison Cafe','Visit Manikaran Gurudwara and dip in hot springs','Drive/trek to Tosh for sunset over the valley'], budget:{backpacker:'₹500–900/day',mid:'₹1,500–3,000/day',luxury:'₹4,000–7,000/day'}, permits:'None for Kasol. Malana entry restricted — respect local rules.', gettingThere:'Bhuntar Airport (31km), bus from Delhi/Chandigarh to Bhuntar then local', climate:{summer:'12–30°C, humid monsoon',winter:'0–12°C, cold but rarely snows'}, tags:['backpacking','cafes','nature','trek'] },
  { id:'kinnaur', image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop', name:'Kinnaur Valley', region:'Kinnaur District', icon:'🍎', color:'#DC2626', difficulty:'Moderate', altitude:'2,320m', temp:'-10°C to 28°C', tagline:'Land of Gods & Apples', description:'Kinnaur — the land between the lush green Sutlej valley and barren Spiti. Famous for Kinnauri apples, Kalpa\'s Kinner Kailash views, Sangla Valley, and the terrifying Hindustan-Tibet Road carved into cliffs. Chitkul (3,450m) is the last Indian village before the Tibetan border.', bestMonths:[4,5,6,9,10], highlights:['Kalpa — sunrise over Kinner Kailash (6,500m)','Chitkul — last village on Indo-Tibet border','Sangla Valley — apple orchards and Kamru Fort','Reckong Peo — gateway town to inner Kinnaur','Hindustan-Tibet Road — India\'s most dramatic highway'], mustDo:['Photograph Kinner Kailash at dawn from Kalpa','Drive the Kinnaur-Spiti circuit via Nako Lake','Buy Kinnauri apples and dry fruits direct from orchards','Visit Kamru Fort\'s wooden temple in Sangla'], budget:{backpacker:'₹800–1,500/day',mid:'₹2,000–3,500/day',luxury:'₹4,000–7,000/day'}, permits:'Inner Line Permit for areas beyond Reckong Peo (free, from DC Reckong Peo).', gettingThere:'Shimla-Rampur-Reckong Peo (10hr), HRTC bus from Delhi/Chandigarh', climate:{summer:'10–28°C, pleasant',winter:'-10 to 8°C, roads risky Dec-Mar'}, tags:['offbeat','photography','apples','culture'] },
  { id:'dalhousie', image:'https://images.unsplash.com/photo-1513220556209-66c30ddde66f?q=80&w=1600&auto=format&fit=crop', name:'Dalhousie', region:'Chamba District', icon:'🌸', color:'#9b59b6', difficulty:'Easy', altitude:'1,970m', temp:'-2°C to 25°C', tagline:'Scotland of India', description:'Built across five hills by the British in 1854 and named after Lord Dalhousie. Pine-covered slopes, colonial churches, and Tibetan market make this a quieter alternative to Shimla. Nearby Khajjiar — often called "Mini Switzerland" — is a saucer-shaped meadow with a small lake surrounded by deodar forest.', bestMonths:[3,4,5,6,9,10], highlights:['Khajjiar — "Mini Switzerland" meadow at 1,951m','St. John\'s Church — beautiful stone church from 1863','Dainkund Peak — highest point in Dalhousie at 2,755m','Kalatop Wildlife Sanctuary — Himalayan black bear territory','Satdhara Falls — seven streams through thick forest'], mustDo:['Walk the Garam Sadak for sunset views','Trek to Dainkund Peak for 360° Dhauladhar views','Horse ride across the Khajjiar meadow','Try rajma-chawal at a local Chamba dhaba'], budget:{backpacker:'₹700–1,200/day',mid:'₹2,000–3,500/day',luxury:'₹4,000–8,000/day'}, permits:'None.', gettingThere:'Pathankot Rail (80km), bus from Delhi (12hr)', climate:{summer:'12–25°C, pleasant',winter:'-2 to 10°C, snowfall Dec-Feb'}, tags:['colonial','nature','photography','quiet'] },
  { id:'bir', image:'https://images.unsplash.com/photo-1610444583163-9a3d45c55209?q=80&w=1600&auto=format&fit=crop', name:'Bir Billing', region:'Kangra District', icon:'🪂', color:'#e67e22', difficulty:'Easy', altitude:'1,525m', temp:'2°C to 32°C', tagline:'Paragliding Capital of India', description:'Bir is the landing site, Billing (2,430m) is the takeoff — together they form Asia\'s best paragliding site, hosting the 2015 Paragliding World Cup. Beyond flying, Bir is a Tibetan colony with monasteries, organic cafes, and an emerging eco-art scene. The Chokling Monastery and Deer Park Institute offer meditation courses.', bestMonths:[3,4,5,6,9,10,11], highlights:['Billing takeoff site — 2,430m with Dhauladhar backdrop','Chokling Monastery — Nyingma school of Tibetan Buddhism','Deer Park Institute — Buddhist studies and meditation','Bir Tea Factory — colonial-era tea processing','Paragliding World Cup venue — international standard'], mustDo:['Tandem paragliding from Billing (₹2,500–3,500)','Meditate at Deer Park Institute','Cycle through Bir\'s Tibetan colony','Sip chai at a roadside stall watching gliders land'], budget:{backpacker:'₹600–1,000/day',mid:'₹1,500–3,000/day',luxury:'₹3,500–6,000/day'}, permits:'None.', gettingThere:'Dharamshala (60km), Pathankot Rail (140km), bus from Delhi (12hr)', climate:{summer:'15–32°C, warm',winter:'2–18°C, clear and crisp'}, tags:['adventure','paragliding','tibetan','cafes'] },
  { id:'chamba', image:'https://images.unsplash.com/photo-1628126235206-5260b9ea6441?q=80&w=1600&auto=format&fit=crop', name:'Chamba', region:'Chamba District', icon:'🛕', color:'#1abc9c', difficulty:'Easy', altitude:'996m', temp:'5°C to 35°C', tagline:'Valley of Temples', description:'One of the oldest hill states in North India, Chamba town sits on a plateau beside the Ravi River. The Chaugan — a kilometer-long promenade — hosts the famous Minjar Fair. Ancient Lakshmi Narayan Temple complex (10th century) and Bhuri Singh Museum preserve Chamba-Pahari miniature paintings and local crafts.', bestMonths:[3,4,5,6,9,10], highlights:['Lakshmi Narayan Temple — 10th century shikhara architecture','Chaugan — historic promenade hosting the Minjar Fair','Bhuri Singh Museum — Chamba rumal embroidery and Pahari art','Akhand Chandi Palace — seat of the Chamba rulers','Chamunda Devi Temple — carved into the hillside'], mustDo:['Visit during Minjar Fair (July/Aug)','Buy authentic Chamba rumal embroidery','Walk the Chaugan at sunset by the Ravi','Try Chamba chukh (spicy chutney) and madra'], budget:{backpacker:'₹500–900/day',mid:'₹1,500–2,500/day',luxury:'₹3,000–5,000/day'}, permits:'None.', gettingThere:'Pathankot Rail (120km), Dalhousie (56km)', climate:{summer:'15–35°C, warm',winter:'5–18°C, pleasant'}, tags:['culture','heritage','temples','art'] },
  { id:'kullu', image:'https://images.unsplash.com/photo-1636173268840-058df89ff658?q=80&w=1600&auto=format&fit=crop', name:'Kullu', region:'Kullu Valley', icon:'🎭', color:'#e74c3c', difficulty:'Easy', altitude:'1,220m', temp:'2°C to 32°C', tagline:'Valley of the Gods', description:'Kullu — the "Valley of the Gods" — is the administrative heart of the Kullu district and host of the legendary Kullu Dussehra, a week-long festival (Oct) where 300+ local deities gather on the Dhalpur Maidan. Surrounded by the Beas River, apple orchards, and ancient temples like Raghunath Temple and Bijli Mahadev.', bestMonths:[3,4,5,6,9,10,11], highlights:['Kullu Dussehra — UNESCO-recognized week-long festival','Bijli Mahadev Temple — lightning-struck Shiv lingam at 2,460m','Great Himalayan National Park — UNESCO World Heritage Site','Naggar Castle — medieval stone-and-wood castle','Raghunath Temple — presiding deity of Kullu kingdom'], mustDo:['Visit during Kullu Dussehra (Oct) for the deity procession','Trek to Bijli Mahadev for Kullu Valley panorama','Explore GHNP on a day hike from Gushaini','Buy Kullu caps and handloom shawls from weavers'], budget:{backpacker:'₹600–1,000/day',mid:'₹1,800–3,000/day',luxury:'₹4,000–7,000/day'}, permits:'GHNP entry ₹50 Indian / ₹200 foreign, plus guide fees.', gettingThere:'Bhuntar Airport (10km), bus from Delhi (12hr)/Chandigarh (8hr)', climate:{summer:'12–32°C, warm and pleasant',winter:'2–15°C, cold nights'}, tags:['culture','festivals','nature','heritage'] }
];

const TREKS = [
  { id:'hampta', image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1600&auto=format&fit=crop', name:'Hampta Pass Trek', difficulty:'Moderate', location:'Manali', region:'Kullu-Lahaul', duration:'5 Days', durationDays:5, distance:'35 km', maxAltitude:'4,270m', cost:'₹8,000–12,000', color:'#C8E600', description:'A dramatic crossover from the lush Kullu Valley to the barren moonscape of Lahaul. Hampta Pass is the perfect introduction to high-altitude trekking — green meadows, river crossings, boulder fields, and the surreal Chandratal Lake side-trip.', bestMonths:[6,7,8,9,10], startPoint:'Jobra, Manali', permits:'None. Chandratal camping fee ₹50.', highlights:['Cross from green Kullu to barren Lahaul in one pass','Camp at Balu Ka Ghera (3,660m) under the stars','Side trip to Chandratal Lake (4,300m)','River crossings over the Rani Nallah','Views of Deo Tibba (6,001m) and Indrasan'], tags:['glacier','meadows','crossover','camping'], itinerary:[{day:1,title:'Manali to Jobra to Chika',desc:'Drive to Jobra (3,100m), trek through forests to Chika campsite.',altitude:'3,100m'},{day:2,title:'Chika to Balu Ka Ghera',desc:'Trek through alpine meadows, cross streams, reach boulder camp.',altitude:'3,660m'},{day:3,title:'Balu Ka Ghera to Shea Goru via Hampta Pass',desc:'Summit day — steep climb to Hampta Pass (4,270m), descend to desert.',altitude:'4,270m → 3,850m'},{day:4,title:'Shea Goru to Chatru',desc:'Descend through Lahaul valley to Chatru roadhead.',altitude:'3,360m'},{day:5,title:'Chatru to Chandratal to Manali',desc:'Optional: drive to Chandratal Lake. Return via Rohtang.',altitude:'4,300m'}] },
  { id:'bhrigu', image:'https://images.unsplash.com/photo-1600010991807-657abeb552ed?q=80&w=1600&auto=format&fit=crop', name:'Bhrigu Lake Trek', difficulty:'Moderate', location:'Manali', region:'Kullu Valley', duration:'4 Days', durationDays:4, distance:'26 km', maxAltitude:'4,300m', cost:'₹5,000–8,000', color:'#5B9BD5', description:'A glacial lake named after sage Bhrigu, sitting at 4,300m surrounded by alpine meadows known as the "grasslands above the treeline." The trek offers non-stop panoramic views of Pir Panjal and Dhauladhar ranges and is accessible from Manali in a weekend.', bestMonths:[5,6,9,10], startPoint:'Gulaba, Manali', permits:'None.', highlights:['Bhrigu Lake at 4,300m — sacred and surreal','360° views of Pir Panjal, Dhauladhar, Hanuman Tibba','Vast rolling alpine meadows with wildflowers','One of the best weekend treks from Manali','Snow-covered lake in early season (May-Jun)'], tags:['lake','meadows','weekend','glacial-lake'], itinerary:[{day:1,title:'Manali to Gulaba to Rola Kholi',desc:'Drive to Gulaba (3,100m), trek through birch and rhododendron forest.',altitude:'3,560m'},{day:2,title:'Rola Kholi to Bhrigu Lake',desc:'Steep climb through meadows to the glacial lake. Camp nearby.',altitude:'4,300m'},{day:3,title:'Bhrigu Lake to Rola Kholi',desc:'Morning at the lake, descend via alternate route with views.',altitude:'3,560m'},{day:4,title:'Rola Kholi to Gulaba to Manali',desc:'Descend through forest, drive back to Manali.',altitude:'3,100m'}] },
  { id:'kheerganga', image:'https://images.unsplash.com/photo-1622308644420-a6e545dff66e?q=80&w=1600&auto=format&fit=crop', name:'Kheerganga Trek', difficulty:'Easy', location:'Kasol', region:'Parvati Valley', duration:'2 Days', durationDays:2, distance:'24 km', maxAltitude:'2,960m', cost:'₹2,000–4,000', color:'#2D6A4F', description:'One of Himachal\'s most popular treks — from Barshaini through dense forests and waterfalls to natural hot springs at the summit. The hot water pool at Kheerganga, believed to be where Lord Shiva meditated for 3,000 years, is the ultimate reward.', bestMonths:[3,4,5,6,9,10,11], startPoint:'Barshaini, Parvati Valley', permits:'None.', highlights:['Natural hot springs at the summit','Rudra Nag waterfall en route','Dense forests of pine, oak, and rhododendron','Views of Parvati Valley from the top','Night camping under clear Himalayan stars'], tags:['hot-springs','waterfall','beginner','camping'], itinerary:[{day:1,title:'Barshaini to Kheerganga',desc:'Trek through Nakthan village, Rudra Nag waterfall, reach hot springs.',altitude:'2,960m'},{day:2,title:'Kheerganga to Barshaini',desc:'Soak in hot springs at dawn, descend via alternate route to Barshaini.',altitude:'1,960m'}] },
  { id:'triund', image:'https://images.unsplash.com/photo-1596522521191-44755106828f?q=80&w=1600&auto=format&fit=crop', name:'Triund Trek', difficulty:'Easy', location:'McLeodGanj', region:'Kangra Valley', duration:'1–2 Days', durationDays:1, distance:'9 km', maxAltitude:'2,875m', cost:'₹1,500–3,000', color:'#FFD54F', description:'The crown jewel of weekend treks in Himachal. A well-marked trail from McLeodGanj through rhododendron and oak forests to a ridge at 2,875m with jaw-dropping views of the snow-capped Dhauladhar range on one side and the Kangra Valley spreading below on the other.', bestMonths:[3,4,5,6,9,10,11,12], startPoint:'Galu Devi Temple, McLeodGanj', permits:'Forest permit ₹50 (Dharamkot checkpoint).', highlights:['Dhauladhar range panorama at arm\'s length','Kangra Valley sunset views','Stargazing from the ridge — zero light pollution','Accessible for beginners','Snowline trek in winter months'], tags:['beginner','ridge','panorama','weekend'], itinerary:[{day:1,title:'McLeodGanj to Triund',desc:'Trek through oak and rhododendron forest, 22 switchbacks to the ridge.',altitude:'2,875m'},{day:2,title:'Triund to McLeodGanj',desc:'Sunrise over Dhauladhar, descend to McLeodGanj by noon.',altitude:'1,770m'}] },
  { id:'pinparvati', image:'https://images.unsplash.com/photo-1626714486580-08709e99a341?q=80&w=1600&auto=format&fit=crop', name:'Pin Parvati Pass', difficulty:'Hard', location:'Kullu-Spiti', region:'Kullu-Spiti', duration:'11 Days', durationDays:11, distance:'110 km', maxAltitude:'5,319m', cost:'₹18,000–25,000', color:'#DC2626', description:'One of the most challenging treks in Himachal — crossing from the lush Parvati Valley to the barren Pin Valley in Spiti over a 5,319m pass. Glaciers, crevasses, boulder fields, river crossings without bridges, and altitude make this a serious mountaineering-grade trek.', bestMonths:[7,8,9], startPoint:'Barshaini, Parvati Valley', permits:'Required from forest department Kullu and SDM Kaza.', highlights:['Cross from Parvati Valley to Pin Valley over the 5,319m pass','Mantalai Lake (4,100m) — source of Parvati River','Glacier crossing on the Parvati side','Complete terrain change from green to desert','One of Himachal\'s most rewarding and toughest treks'], tags:['glacier','extreme','crossover','advanced'], itinerary:[{day:1,title:'Barshaini to Kheerganga',desc:'Trek through Parvati Valley to hot springs base.',altitude:'2,960m'},{day:2,title:'Kheerganga to Tunda Bhuj',desc:'Dense forest trek, river crossings.',altitude:'3,200m'},{day:3,title:'Tunda Bhuj to Thakur Kuan',desc:'Narrow valley, waterfall crossings.',altitude:'3,500m'},{day:4,title:'Thakur Kuan to Odi Thach',desc:'Open meadows, boulder fields.',altitude:'3,700m'},{day:5,title:'Odi Thach to Mantalai Lake',desc:'Source of Parvati River, stunning glacial lake.',altitude:'4,100m'},{day:6,title:'Rest day at Mantalai',desc:'Acclimatization. Explore the lake.',altitude:'4,100m'},{day:7,title:'Mantalai to Base Camp',desc:'Steep moraine climb to glacier base.',altitude:'4,600m'},{day:8,title:'Base Camp to Pin Parvati Pass to Pin Side',desc:'Summit day. Glacier and crevasse crossing.',altitude:'5,319m → 4,800m'},{day:9,title:'Descent to Mud Village',desc:'Descend into Pin Valley — barren desert landscape.',altitude:'3,700m'},{day:10,title:'Mud to Gulling',desc:'Walk through Pin Valley villages.',altitude:'3,500m'},{day:11,title:'Gulling to Kaza',desc:'Drive or trek to Kaza in Spiti.',altitude:'3,640m'}] },
  { id:'prashar', image:'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?q=80&w=1600&auto=format&fit=crop', name:'Prashar Lake Trek', difficulty:'Easy', location:'Mandi', region:'Mandi District', duration:'1–2 Days', durationDays:1, distance:'9 km', maxAltitude:'2,730m', cost:'₹1,500–3,000', color:'#9b59b6', description:'A serene, floating-island lake at 2,730m with a 13th-century pagoda-style temple dedicated to sage Prashar. The lake has a floating island that moves mysteriously across the surface. Snow-capped Dhauladhar and Pir Panjal views, and one of the best winter treks in Himachal.', bestMonths:[1,2,3,4,5,9,10,11,12], startPoint:'Bagi (30 km from Mandi)', permits:'None.', highlights:['Floating island that moves across the lake','13th-century three-tiered pagoda temple','360° views of Dhauladhar, Pir Panjal, Kinnaur Kailash','One of the best winter treks in Himachal','Camp beside the lake under Milky Way'], tags:['lake','temple','winter','weekend'], itinerary:[{day:1,title:'Bagi to Prashar Lake',desc:'Trek through deodar forest and meadows to the sacred lake.',altitude:'2,730m'},{day:2,title:'Prashar Lake to Bagi',desc:'Sunrise at the temple, explore floating island, descend.',altitude:'1,600m'}] },
  { id:'chandrakhani', image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop', name:'Chandrakhani Pass', difficulty:'Moderate', location:'Naggar', region:'Kullu Valley', duration:'4 Days', durationDays:4, distance:'32 km', maxAltitude:'3,660m', cost:'₹6,000–9,000', color:'#e67e22', description:'An ancient trade route from Kullu to Malana, crossing the Chandrakhani Pass at 3,660m. The trek passes through pristine deodar forests and vast meadows, ending at the enigmatic Malana village — one of the oldest democracies in the world with its own language and customs.', bestMonths:[5,6,9,10], startPoint:'Naggar, Kullu Valley', permits:'None. Malana has strict entry rules — do not touch anyone or anything without permission.', highlights:['Cross into the secretive Malana village','Pass through ancient deodar forests and alpine meadows','Views of Deo Tibba, Parbati South, and the Kullu Valley','Camp at the beautiful Nag Dhar meadow','One of the oldest trade routes in the region'], tags:['meadows','cultural','crossover','ancient-route'], itinerary:[{day:1,title:'Naggar to Rumsu',desc:'Trek from Naggar Castle through villages and oak forest.',altitude:'2,200m'},{day:2,title:'Rumsu to Nag Dhar',desc:'Ascend through deodar forest to open meadows.',altitude:'3,100m'},{day:3,title:'Nag Dhar to Chandrakhani Pass to Malana',desc:'Cross the pass with panoramic views, descend to Malana.',altitude:'3,660m → 2,650m'},{day:4,title:'Malana to Jari',desc:'Descend from Malana to Jari in Parvati Valley.',altitude:'1,580m'}] },
  { id:'beaskund', image:'https://images.unsplash.com/photo-1610444583163-9a3d45c55209?q=80&w=1600&auto=format&fit=crop', name:'Beas Kund Trek', difficulty:'Moderate', location:'Manali', region:'Kullu Valley', duration:'4 Days', durationDays:4, distance:'24 km', maxAltitude:'3,690m', cost:'₹5,000–8,000', color:'#1abc9c', description:'Trek to the glacial source of the Beas River — the Beas Kund (lake). The trail passes through meadows of Dhundi and Bakarthach with views of Shitidhar, Friendship Peak, Hanuman Tibba, and the Pir Panjal range. A classic moderate trek accessible from Manali.', bestMonths:[5,6,7,9,10], startPoint:'Solang Valley, Manali', permits:'None.', highlights:['Source of the sacred Beas River','Views of Friendship Peak, Shitidhar, Ladakhi Peak','Camp at flower-carpeted Bakarthach meadow','Boulder scramble to the glacial lake','Accessible moderate trek from Manali'], tags:['glacial-lake','meadows','river-source','moderate'], itinerary:[{day:1,title:'Solang to Dhundi',desc:'Trek from Solang through forests to Dhundi meadow.',altitude:'3,050m'},{day:2,title:'Dhundi to Bakarthach',desc:'Open meadows, stream crossings, wildflower carpets.',altitude:'3,380m'},{day:3,title:'Bakarthach to Beas Kund and back',desc:'Boulder scramble to the glacial lake. Return to camp.',altitude:'3,690m'},{day:4,title:'Bakarthach to Solang',desc:'Descend through meadows and forest to Solang Valley.',altitude:'2,480m'}] }
];

const RESORTS = [
  { id:'span-resort', name:'Span Resort & Spa', location:'Kullu', image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1600&auto=format&fit=crop', price:'₹25,000/night', rating:'4.9', features:'["River Front", "Heliport", "Luxury Spa"]', description:'Nestled along the fast-flowing Beas river in Kullu. Offers 5-star luxury, vast walnut orchards, and ultimate relaxation.' },
  { id:'wildflower', name:'Wildflower Hall, Shimla', location:'Mashobra, Shimla', image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1600&auto=format&fit=crop', price:'₹28,000/night', rating:'4.9', features:['Indoor Heated Pool', 'Luxury Spa', 'Cedar Forest Views'], description:'An Oberoi resort set in 22 acres of virgin cedar and pine forests at 8,250 ft. Former residence of Lord Kitchener, now one of India\'s finest luxury retreats.' },
  { id:'oberoi-cecil', name:'The Oberoi Cecil', location:'Shimla', image:'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1600&auto=format&fit=crop', price:'₹22,000/night', rating:'4.8', features:['Heritage Property', 'Valley Views', 'Michelin-Style Dining'], description:'A grand heritage hotel on Mall Road since 1884. Restored Edwardian elegance with teak floors, Burma teak furniture, and panoramic Shimla valley views.' },
  { id:'taj-theog', name:'Taj Theog Resort & Spa', location:'Theog, Shimla', image:'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1600&auto=format&fit=crop', price:'₹32,000/night', rating:'4.9', features:['Infinity Pool', '360° Mountain Views', 'Jiva Spa'], description:'Perched on a ridge at 7,200 ft, this Taj property offers unparalleled views of snow-capped peaks and the Sutlej valley. Home to the signature Jiva Spa.' },
  { id:'the-himalayan', name:'The Himalayan, Manali', location:'Manali', image:'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1600&auto=format&fit=crop', price:'₹20,000/night', rating:'4.8', features:['Gothic Architecture', 'Cherry Orchards', 'Antique Library'], description:'An 1890s manor built in Victorian Gothic Revival style, set amidst apple and cherry orchards with views of the Beas Valley. Features original antique furnishings.' },
  { id:'rakkh-resort', name:'Rakkh Resort', location:'Solan', image:'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=1600&auto=format&fit=crop', price:'₹18,000/night', rating:'4.7', features:['Eco Luxury', 'Farm-to-Table', 'Infinity Pool'], description:'A boutique eco-resort on 12 acres of pine forest in Solan. Features an infinity pool overlooking the Shivalik hills, organic farm, and artisanal stone cottages.' },
  { id:'castle-naggar', name:'Castle Naggar', location:'Naggar, Kullu', image:'https://images.unsplash.com/photo-1587061949409-02df41d5e562?q=80&w=1600&auto=format&fit=crop', price:'₹8,000/night', rating:'4.7', features:['Medieval Castle', 'Roerich Gallery', 'Valley Panorama'], description:'A 500-year-old stone castle converted to a heritage hotel by HPTDC. Nicholas Roerich\'s art gallery is next door. Unmatched views of the entire Kullu Valley.' },
  { id:'zostel-spiti', name:'Grand Shangri-La, Kaza', location:'Kaza, Spiti', image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1600&auto=format&fit=crop', price:'₹6,500/night', rating:'4.6', features:['High Altitude', 'Stargazing Deck', 'Spitian Cuisine'], description:'At 3,800m in the heart of Spiti Valley, this boutique stay combines traditional mud-brick architecture with modern comfort. The stargazing deck is legendary.' },
  { id:'lodge-at-wah', name:'The Lodge at Wah', location:'Palampur', image:'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=1600&auto=format&fit=crop', price:'₹16,000/night', rating:'4.9', features:['Tea Estate', 'Organic Farm', 'Kangra Valley Views'], description:'An eco-luxury homestay inside Wah Tea Estate — the largest working tea plantation in Kangra Valley. Organic meals, misty mornings, and Dhauladhar sunsets.' }
];

const SEASONS = [
  {month:1,name:'January',season:'Peak Winter',emoji:'❄️',temp:'-8°C to 10°C',beauty:4,crowd:2,accessibility:2,longDesc:'Heavy snowfall blankets Shimla, Manali, and Dalhousie. Spiti roads are closed. Ideal for snow lovers and Prashar Lake winter trek. Skiing at Solang.', openDest:['Shimla','Manali','Dalhousie','Dharamshala','Prashar Lake'], closedDest:['Spiti Valley','Kinnaur (risky)','Rohtang Pass','High-altitude treks'], highlights:['Fresh snowfall in Manali and Shimla','Prashar Lake winter trek — snow blanket','Skiing and snowboarding at Solang Valley','New Year celebrations in hill towns']},
  {month:2,name:'February',season:'Late Winter',emoji:'🌨️',temp:'-5°C to 12°C',beauty:4,crowd:2,accessibility:2,longDesc:'Snow persists in higher regions. Roads to Spiti still closed. Great month for snow treks and photography. Fewer crowds.', openDest:['Shimla','Manali','Dalhousie','Kasol','Dharamshala'], closedDest:['Spiti Valley','Kinnaur','Hampta Pass','High passes'], highlights:['Shivratri celebrations across temples','Off-season discounts on stays','Snow photography in Kullu Valley','Quiet trails for experienced trekkers']},
  {month:3,name:'March',season:'Early Spring',emoji:'🌸',temp:'2°C to 20°C',beauty:4,crowd:3,accessibility:3,longDesc:'Snow melts in lower hills. First blooms of rhododendron and wild cherry. Great for Triund, Prashar Lake, and lower valley treks.', openDest:['All lower valleys','Dharamshala','Kasol','Shimla','Bir Billing'], closedDest:['Spiti (still closed)','High passes above 4,000m'], highlights:['Cherry blossoms in Shimla and Kullu','Holi celebrations with local twists','Rhododendron blooms on Triund trail','Season opening for paragliding in Bir']},
  {month:4,name:'April',season:'Spring',emoji:'🌷',temp:'8°C to 25°C',beauty:5,crowd:3,accessibility:4,longDesc:'Full spring — wildflowers carpet the meadows. Apple orchards blossom in Kinnaur and Kullu. Perfect trekking weather for moderate treks. Rohtang may open late April.', openDest:['All destinations except inner Spiti','Kinnaur opens','Manali','Shimla','Kasol'], closedDest:['Inner Spiti (Kaza)','Chandratal'], highlights:['Apple blossom season in Kinnaur and Kullu','Baisakhi — harvest festival celebrated statewide','Wildflower meadows on Bhrigu Lake trail','Perfect weather for all day treks']},
  {month:5,name:'May',season:'Late Spring',emoji:'☀️',temp:'12°C to 30°C',beauty:5,crowd:4,accessibility:4,longDesc:'Peak summer tourism begins. Manali and Shimla bustle. Rohtang opens. Green valleys, clear skies. Best time for Bhrigu Lake, Beas Kund, and starting high-altitude treks.', openDest:['All destinations including Kinnaur','Rohtang Pass','All moderate treks'], closedDest:['Spiti (opening late May via Shimla route)'], highlights:['Summer break rush — book early','Rohtang Pass opens for the season','Bhrigu Lake trek in partial snow','Crystal clear views of Dhauladhar']},
  {month:6,name:'June',season:'Early Summer',emoji:'🌞',temp:'15°C to 32°C',beauty:5,crowd:5,accessibility:5,longDesc:'All passes open. Spiti accessible via both routes. Best month for high-altitude treks — Hampta Pass, Pin Parvati, Chandrakhani. Apple orchards in full green. Monsoon arrives late June.', openDest:['Everything open','Spiti fully accessible','All treks open'], closedDest:['None — everything accessible'], highlights:['Hampta Pass and Bhrigu Lake at their best','Spiti roads open via Manali and Shimla','International Paragliding Festival in Bir','Last window before monsoon rains']},
  {month:7,name:'July',season:'Monsoon',emoji:'🌧️',temp:'15°C to 28°C',beauty:3,crowd:2,accessibility:2,longDesc:'Heavy monsoon in lower and mid hills — landslides common on Kullu-Manali, Shimla, and Kangra roads. Spiti remains dry (rain shadow). Lush green everywhere. Minjar Fair in Chamba.', openDest:['Spiti (dry)','Lahaul','Chamba (Minjar Fair)'], closedDest:['Manali roads risky','Kasol landslide-prone','Most treks closed'], highlights:['Spiti is dry and stunning during monsoon','Minjar Fair — Chamba\'s biggest celebration','Lush green valleys for photography','Off-season rates in most towns']},
  {month:8,name:'August',season:'Peak Monsoon',emoji:'⛈️',temp:'14°C to 26°C',beauty:3,crowd:2,accessibility:2,longDesc:'Heaviest rains. Landslides disrupt roads to Manali, Shimla, Kinnaur. Spiti remains the best bet. Independence Day celebrations. Waterfalls at peak flow.', openDest:['Spiti Valley','Lahaul','Upper Kinnaur (carefully)'], closedDest:['Lower Himachal risky','Most treks','Kasol area'], highlights:['Spiti — best monsoon escape in India','Independence Day celebrations in hill towns','Waterfalls everywhere at full force','Mushroom foraging season in forests']},
  {month:9,name:'September',season:'Post-Monsoon',emoji:'🌤️',temp:'10°C to 25°C',beauty:5,crowd:3,accessibility:4,longDesc:'Rains recede, valleys gleam emerald. Clearest mountain views of the year. Trek season reopens — Hampta, Bhrigu, Chandrakhani. Apple harvest begins in Kinnaur.', openDest:['All destinations reopening','All moderate treks','Kinnaur apple season'], closedDest:['High passes closing by late Sept'], highlights:['Clearest Himalayan views of the year','Trek season reopens — book now','Apple harvest in Kinnaur','Kullu Dussehra preparations begin']},
  {month:10,name:'October',season:'Autumn',emoji:'🍂',temp:'5°C to 22°C',beauty:5,crowd:4,accessibility:4,longDesc:'Golden autumn — the best month for Himachal. Clear skies, golden oak forests, harvest festivals. Kullu Dussehra (week-long) is the highlight. Last window for high-altitude treks before snow.', openDest:['All lower and mid-altitude destinations','Treks until mid-Oct'], closedDest:['Spiti closing late Oct','Rohtang closes by Nov'], highlights:['Kullu Dussehra — 7-day deity festival (UNESCO)','Golden autumn foliage across all valleys','Best photography month','Last chance for Hampta Pass and Bhrigu Lake']},
  {month:11,name:'November',season:'Early Winter',emoji:'🍁',temp:'0°C to 15°C',beauty:3,crowd:2,accessibility:3,longDesc:'First snowfall in high areas. Spiti roads closing. Quiet hill stations with off-season rates. Clear days and cold nights. Triund and Prashar still accessible.', openDest:['Shimla','Manali (pre-snow)','Dharamshala','Dalhousie','Kasol'], closedDest:['Spiti Valley','Kinnaur inner','Rohtang Pass','High treks'], highlights:['First snowfall excitement','Off-season peace and discounts','Prashar Lake trek before heavy snow','Diwali celebrations in hill towns']},
  {month:12,name:'December',season:'Winter',emoji:'⛷️',temp:'-5°C to 10°C',beauty:4,crowd:3,accessibility:2,longDesc:'Snow season begins properly. Shimla and Manali transform into winter wonderlands. Christmas and New Year tourism peaks. Skiing opens at Solang. Inner routes closed.', openDest:['Shimla','Manali','Dalhousie','Dharamshala'], closedDest:['Spiti','Kinnaur','All high-altitude treks','Rohtang'], highlights:['Christmas in Shimla — snow and colonial charm','New Year celebrations in Manali','Skiing opens at Solang Valley','Snow treks: Prashar Lake, Triund']}
];

const WILDLIFE = [
  {icon:'🦅',id:'himalayan_monal', name:'Himalayan Monal',latin:'Lophophorus impejanus',desc:'The state bird of Himachal Pradesh. Males display iridescent plumage of green, blue, copper, and purple. Found in GHNP, Kullu forests, and high alpine meadows between 2,500–5,000m.',status:'Least Concern',tags:['State Bird','GHNP','Alpine']},
  {icon:'🐆',id:'snow_leopard', name:'Snow Leopard',latin:'Panthera uncia',desc:'The "Ghost of the Mountains" inhabits Spiti and upper Kinnaur at 3,500–5,500m. Pin Valley National Park and Kibber Wildlife Sanctuary are prime habitats. Estimated 40–50 in Himachal.',status:'Vulnerable',tags:['Spiti','Pin Valley','Rare']},
  {icon:'🐻',id:'himalayan_brown_bear', name:'Himalayan Brown Bear',latin:'Ursus arctos isabellinus',desc:'Found in Kugti Wildlife Sanctuary (Chamba) and upper Kullu. Larger than the Asiatic black bear. Hibernates Oct-Mar. Critically endangered in Himachal with less than 100 individuals.',status:'Critically Endangered',tags:['Kugti','Rare','Chamba']},
  {icon:'🦌',id:'himalayan_musk_deer', name:'Himalayan Musk Deer',latin:'Moschus chrysogaster',desc:'Shy, solitary deer found in birch and rhododendron forests of GHNP and Tirthan Valley at 2,500–4,500m. Males have elongated canine tusks. Severely poached for musk glands.',status:'Endangered',tags:['GHNP','Tirthan','Poached']},
  {icon:'🐐',id:'himalayan_tahr', name:'Himalayan Tahr',latin:'Hemitragus jemlahicus',desc:'Sure-footed wild goat found on steep, rocky slopes of the Dhauladhar and Pir Panjal ranges. Males have thick reddish-brown mane. Best seen in GHNP and Churdhar Sanctuary.',status:'Near Threatened',tags:['Dhauladhar','GHNP','Alpine']},
  {icon:'🐦',id:'western_tragopan', name:'Western Tragopan',latin:'Tragopan melanocephalus',desc:'The rarest of all pheasants, found only in western Himalayas. GHNP is its stronghold in Himachal — estimated 300 birds. Colorful crimson and black plumage with blue facial skin.',status:'Vulnerable',tags:['GHNP only','Rarest Pheasant','Protected']},
  {icon:'🦊',id:'red_fox', name:'Red Fox',latin:'Vulpes vulpes montana',desc:'Common across Spiti, Lahaul, and high-altitude meadows. Adapted to extreme cold with thick fur. Often spotted near campsites on treks like Hampta Pass and Chandratal.',status:'Least Concern',tags:['Spiti','Common','Adaptable']},
  {icon:'🐏',id:'bharal_(blue_sheep', name:'Bharal (Blue Sheep)',latin:'Pseudois nayaur',desc:'Primary prey of the snow leopard. Large herds graze on steep cliffs in Spiti, Pin Valley, and upper Kinnaur. Blue-grey coat blends perfectly with rocky terrain.',status:'Least Concern',tags:['Spiti','Pin Valley','Snow Leopard prey']},
  {icon:'🦅',id:'lammergeier', name:'Lammergeier',latin:'Gypaetus barbatus',desc:'The bearded vulture — massive wingspan of up to 2.8m. Drops bones from height to crack them for marrow. Seen soaring above Spiti, Kinnaur, and Dhauladhar ranges.',status:'Near Threatened',tags:['Spiti','Kinnaur','Bone-breaker']},
  {icon:'🐒',id:'himalayan_langur', name:'Himalayan Langur',latin:'Semnopithecus ajax',desc:'Grey langur with silver-tipped fur found in temperate forests of Shimla, Manali, and Dharamshala. Often seen near temples and tourist areas. Sacred to locals.',status:'Near Threatened',tags:['Common','Temples','Forests']}
];

const WILDLIFE_FACTS = [
  'Great Himalayan National Park (GHNP) in Kullu is a UNESCO World Heritage Site — one of only two natural sites in India.',
  'Himachal has 33 wildlife sanctuaries and 2 national parks protecting over 800 species of flora and fauna.',
  'The Himalayan Monal can be spotted at 4,000m+ and is the state bird feature on the HP government emblem.',
  'Pin Valley National Park in Spiti is the only park in India where you can reliably spot snow leopards and bharal.',
  'HP is home to over 950 bird species — one of the richest avian regions in the world.',
  'The Western Tragopan nests only in GHNP and is the world\'s rarest pheasant species.',
  'Kugti Wildlife Sanctuary in Chamba is the last stronghold of the Himalayan brown bear in Himachal.',
  'The red fox of Spiti has adapted to survive at 5,000m — one of the highest-living mammals on earth.'
];

const CULTURE = {
  etiquette: [
    {icon:'🙏',title:'Namaste First',text:'Greet locals with "Namaste ji" or "Sat Sri Akal" (in Kangra). In Spiti, "Julley" is the greeting. Elders are addressed respectfully.'},
    {icon:'🛕',title:'Temple Protocol',text:'Remove shoes before entering temples. Walk clockwise around Buddhist stupas and monasteries. Cover shoulders and knees. Ask before photographing deities.'},
    {icon:'🏠',title:'Homestay Customs',text:'Accept chai when offered — declining is considered rude. In Spiti and Kinnaur, sitting cross-legged on the floor at meals is customary.'},
    {icon:'🚮',title:'Leave No Trace',text:'Himachali communities take pride in clean mountains. Carry back all waste. Burning garbage at altitude releases toxic fumes — pack it out.'},
    {icon:'🌿',title:'Sacred Groves',text:'Many forests in Himachal are "dev vans" — sacred groves protected by village deities. Do not cut trees, pick flowers, or disturb stones in marked areas.'},
    {icon:'🐄',title:'Respect Animals',text:'Cows roam freely in most towns. In Spiti, yaks are working animals — do not feed them human food. Dogs at dhabas are community pets.'},
    {icon:'📸',title:'Ask Before Photos',text:'Always ask before photographing people, especially women, monks, and elderly. In Malana, do not touch any person, structure, or wall.'},
    {icon:'💧',title:'Water Sources',text:'Natural springs (chasma) are considered sacred. Do not wash clothes, utensils, or use soap near any water source.'}
  ],
  foods: [
    {id:'dham', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Dham',desc:'Himachal\'s grand festive feast — rajma, madra (chickpeas in yogurt gravy), moong dal, rice, and meetha (sweet). Served on pattal (leaf plates) by Botis (hereditary cooks).',region:'All districts — every festival and wedding'},
    {id:'siddu', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Siddu',desc:'Steamed wheat bread stuffed with poppy seed paste or walnuts, served with ghee and green chutney. A Kullu-Mandi specialty.',region:'Kullu, Mandi'},
    {id:'madra', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Madra',desc:'Soaked chickpeas slow-cooked in yogurt with cardamom, cinnamon, and cloves. The signature dish of Chamba and Kangra.',region:'Chamba, Kangra'},
    {id:'babru', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Babru',desc:'Deep-fried kachori stuffed with urad dal paste. Served with tamarind chutney. Shimla\'s beloved street food.',region:'Shimla, Sirmour'},
    {id:'aktori', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Aktori',desc:'Sweet buckwheat pancake from Spiti, made during Losar festival. Mixed with sugar and ghee — a rare Spitian delicacy.',region:'Spiti, Lahaul'},
    {id:'chha_gosht', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Chha Gosht',desc:'Slow-cooked lamb marinated in gram flour and yogurt gravy. A Chamba royal dish served at special occasions.',region:'Chamba'},
    {id:'patande', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Patande',desc:'Himachali-style crepe made from rice batter, folded with jaggery filling. Prepared during Makar Sankranti.',region:'Mandi, Kullu, Shimla'},
    {id:'thukpa_and_momos', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Thukpa & Momos',desc:'Tibetan noodle soup and steamed dumplings — staple in Spiti, Lahaul, Dharamshala, and every hill backpacker cafe.',region:'Spiti, Lahaul, McLeodGanj'},
    {id:'tudkiya_bhath', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Tudkiya Bhath',desc:'Himachali flavored rice with lentils, potatoes, onion, and whole spices. A one-pot comfort meal from the hills.',region:'Mandi, Kullu'},
    {id:'mittha', image:'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=1600&auto=format&fit=crop', name:'Mittha',desc:'Sweetened rice with raisins, dry fruits, and saffron — the dessert course of every Dham feast.',region:'All districts'}
  ],
  altitudeTips: [
    {altitude:'Up to 2,500m (Shimla, Kasol, Dharamshala)',risk:'Low',advice:'No acclimatization needed. Stay hydrated, avoid alcohol on arrival day. Enjoy freely.'},
    {altitude:'2,500m–3,500m (Manali, Triund, Kheerganga)',risk:'Moderate',advice:'Mild headaches possible. Drink 3–4 liters water daily. Avoid rushing uphill. Garlic soup helps — ask at dhabas.'},
    {altitude:'3,500m–4,500m (Spiti, Bhrigu Lake, Hampta Pass)',risk:'High',advice:'Mandatory 1 rest day before exertion. Diamox (125mg) can help — consult doctor before trip. Watch for nausea, persistent headache.'},
    {altitude:'Above 4,500m (Pin Parvati, Chandratal)',risk:'Very High',advice:'Serious AMS risk. Ascend max 500m/day above 3,500m. Never ignore symptoms — descend immediately if worsening. Carry Diamox and oxygen.'}
  ],
  packingList: {
    clothing:['Layered thermals (Decathlon works)','Waterproof jacket (mandatory monsoon)','Fleece or down jacket for 3,000m+','Quick-dry trek pants (2 pairs)','Warm cap, gloves, neck gaiter','Sturdy trekking shoes (broken in)'],
    gear:['35–50L backpack with rain cover','Trekking poles (essential for knees)','Headlamp with extra batteries','Water bottle + Aquatabs/LifeStraw','Sleeping bag rated -5°C for treks','Sunscreen SPF50+ and lip balm'],
    health:['Diamox for altitude (prescription)','ORS sachets','Basic first aid kit','Personal medications','Toilet paper and hand sanitizer'],
    documents:['Aadhar/Passport (Inner Line Permit areas)','2 passport-size photos (permits)','Trek booking confirmation','HRTC bus tickets or Volvo booking','Travel insurance with altitude cover']
  },
  emergency: [
    {name:'Himachal Police',number:'100 / 112'},
    {name:'HRTC Helpline',number:'0177-265-6093'},
    {name:'GHNP Rescue (Kullu)',number:'01902-265-320'},
    {name:'DC Kaza (Spiti permits/rescue)',number:'01906-222-367'},
    {name:'IGMC Hospital Shimla',number:'0177-280-3073'},
    {name:'Ambulance (HP)',number:'108'}
  ]
};

const FESTIVALS = [
  {id:'kullu_dussehra', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Kullu Dussehra',month:'October',icon:'🎭',desc:'Week-long festival where 300+ village deities are carried in processions to Dhalpur Maidan. Starts when India\'s Dussehra ends. UNESCO heritage recognition.',location:'Kullu'},
  {id:'minjar_fair', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Minjar Fair',month:'July–August',icon:'🌾',desc:'Chamba\'s ancient harvest festival celebrating the maize and paddy crop. Silk thread "minjar" offered to Ravi River. Week-long fair with music and dance.',location:'Chamba'},
  {id:'lavi_fair', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Lavi Fair',month:'November',icon:'🏪',desc:'One of India\'s oldest trade fairs — 300+ years. Merchants from Tibet, Kinnaur, and plains gather. Cultural performances, wrestling, and commerce.',location:'Rampur Bushahr'},
  {id:'losar_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Losar Festival',month:'February',icon:'🎉',desc:'Tibetan New Year celebrated with masked Cham dances, prayers, feasting on aktori (buckwheat cake), and monastery ceremonies in Spiti and Lahaul.',location:'Spiti, Lahaul'},
  {id:'fagli_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Fagli Festival',month:'February',icon:'👹',desc:'Kinnauri spring festival with masked devil dances, bonfires, and community feasting. Local brew "chhang" flows freely. Pre-dates recorded history.',location:'Kinnaur'},
  {id:'halda_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Halda Festival',month:'January',icon:'🔥',desc:'Lahaul\'s winter solstice celebration with bonfire rituals, folk songs, and the Halda dance. Communities gather to ward off evil spirits.',location:'Lahaul'},
  {id:'shivratri_fair', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Shivratri Fair',month:'February–March',icon:'🕉️',desc:'Mandi hosts one of India\'s largest Shivratri fairs — 200+ deities brought to town. Week-long cultural programs, trade fair, and temple rituals.',location:'Mandi'},
  {id:'sazo_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Sazo Festival',month:'September',icon:'🌺',desc:'Kinnaur\'s flower festival celebrating the autumn bloom. Villagers offer flowers at temples, dance to traditional Nati, and feast on local dishes.',location:'Kinnaur'},
  {id:'pori_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Pori Festival',month:'April',icon:'🎶',desc:'New Year celebration in Kinnaur with archery contests, Nati dance, and feasting. Marks the start of the agricultural season.',location:'Kinnaur'},
  {id:'international_himalayan_festival', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'International Himalayan Festival',month:'December',icon:'🙏',desc:'Celebrates the Dalai Lama\'s Nobel Peace Prize. Three days of Tibetan music, dance, art exhibitions, and teachings in McLeodGanj.',location:'McLeodGanj, Dharamshala'},
  {id:'summer_festival_shimla', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Summer Festival Shimla',month:'May–June',icon:'🎵',desc:'Cultural extravaganza with folk music, handicraft exhibitions, flower shows, and adventure sports. Celebrates Shimla\'s colonial-era heritage.',location:'Shimla'},
  {id:'nati_dance_gatherings', image:'https://images.unsplash.com/photo-1528643036987-9bfa6a12bcca?w=1600&auto=format&fit=crop', name:'Nati Dance Gatherings',month:'Year-round',icon:'💃',desc:'Himachal\'s traditional folk dance — performed at every festivity. Kullu Nati holds the Guinness record for largest folk dance (9,892 dancers in 2015).',location:'Statewide'}
];

const LANGUAGES = [
  {name:'Pahari (Himachali)',region:'Statewide — the mother tongue',script:'प',phrases:[{local:'Kaise ho?',english:'How are you?'},{local:'Shukriya ji',english:'Thank you'},{local:'Kidhar jaana hai?',english:'Where are you going?'}]},
  {name:'Kangri',region:'Kangra Valley, Dharamshala, Palampur',script:'ਕ',phrases:[{local:'Ki haal hai?',english:'How are you?'},{local:'Tussi kithon aaye?',english:'Where are you from?'},{local:'Bohut vadiya',english:'Very good'}]},
  {name:'Kinnauri',region:'Kinnaur District',script:'ཀ',phrases:[{local:'Aachho',english:'Hello/Welcome'},{local:'Thuk-je-che',english:'Thank you'},{local:'Sho-na-tang',english:'Beautiful place'}]},
  {name:'Spitian (Bhoti)',region:'Spiti Valley, Lahaul',script:'བ',phrases:[{local:'Julley',english:'Hello/Goodbye'},{local:'Julley khamzang?',english:'How are you?'},{local:'Thuk-je-che',english:'Thank you'}]},
  {name:'Chambyali',region:'Chamba District',script:'छ',phrases:[{local:'Ki haala chala?',english:'What\'s happening?'},{local:'Aiye ji baitho',english:'Come, sit down'},{local:'Bohut achha',english:'Very nice'}]},
  {name:'Mandeali',region:'Mandi District',script:'म',phrases:[{local:'Kina haal baal?',english:'How\'s everything?'},{local:'Khetru ja rahe?',english:'Where are you going?'},{local:'Bas theek hai',english:'All is well'}]}
];

const BUDGET_GUIDE = [
  {title:'Backpacker',range:'₹800–1,500/day',desc:'Dorm beds, shared guesthouses, dhaba meals, HRTC buses, trekking without guides.',details:['Dorm/budget room: ₹300–600','Thali meal: ₹80–150','HRTC bus Chandigarh-Manali: ₹600–800','Local meal at dhaba: ₹100–200','Self-guided treks: free (just food and stay)']},
  {title:'Mid-Range',range:'₹2,500–5,000/day',desc:'Private hotel rooms, restaurant meals, tempo traveler/Volvo buses, guided treks with gear.',details:['Hotel room: ₹1,500–3,000','Restaurant meal: ₹300–600','Volvo Deluxe Delhi-Manali: ₹1,200–1,600','Guided trek per day: ₹1,500–2,500','Paragliding Bir: ₹2,500–3,500']},
  {title:'Luxury',range:'₹8,000–20,000/day',desc:'Heritage hotels, boutique stays, private vehicles, premium guided experiences.',details:['Boutique hotel: ₹5,000–15,000','Fine dining: ₹1,000–2,500','Private taxi Chandigarh-Manali: ₹5,000–7,000','Premium guided trek with porter: ₹4,000–6,000/day','Helicopter to Spiti (charter): ₹80,000+']}
];

const PERMITS_GUIDE = [
  {region:'Spiti Valley',title:'Inner Line Permit',desc:'Free ILP required beyond Sumdo on the Shimla-Kaza route and for areas near Indo-Tibetan border. Apply at DC Kaza or DC Reckong Peo. Indian nationals only — foreigners apply at DC Shimla.',tips:'Apply online at hpipr.hp.gov.in or in person at DC office. Carry 2 passport photos and Aadhar/passport.'},
  {region:'Kinnaur',title:'Inner Line Permit',desc:'Required beyond Reckong Peo towards Chitkul and Spiti border. Free for Indians, small fee for foreigners. Apply at DC Reckong Peo or Shimla.',tips:'Road conditions change daily — check HRTC and BRO updates before starting.'},
  {region:'Rohtang Pass',title:'Vehicle Permit',desc:'₹550 per vehicle for crossing Rohtang (Manali to Lahaul). Book online at rohtangpermits.nic.in. Daily cap of 1,200 vehicles.',tips:'Book 1–3 days in advance. Permits released at 4 PM for next day. Atal Tunnel has separate toll but no permit needed.'},
  {region:'GHNP',title:'Park Entry',desc:'Great Himalayan National Park entry: ₹50 Indians / ₹200 foreigners. Mandatory guide fee extra. Multi-day treks inside GHNP require registration.',tips:'Hire GHNP-certified guides from Sai Ropa office. Inside the park, no fires allowed — carry stoves.'},
  {region:'Malana',title:'Village Entry',desc:'Malana village has strict customary rules. Do not touch anyone, any wall, or any structure. Stay on the designated path. No loud music or disrespectful behavior.',tips:'The village can close entry without notice. Respect is not optional here — it\'s a 4,000-year-old self-governing community.'}
];

const SERVICES = [
  // KULLU SPECIFIC SERVICES
  { id:'cab-kullu-airport', category:'cabs', image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0be2?w=1600&auto=format&fit=crop', name:'Bhuntar Airport Taxis', area:'Kullu Airport', price:'₹1,200–2,500', description:'Premium luxury cabs and sedans directly from Bhuntar Airport to Kullu, Naggar, or Tirthan Valley.', phone:'+919876500091', whatsapp:'919876500091', icon:'🚖', tags:['kullu','airport','luxury'] },
  { id:'raft-kullu', category:'paragliding', image:'https://images.unsplash.com/photo-1537249010077-e2f0d96d2e90?w=1600&auto=format&fit=crop', name:'Beas River Rafting', area:'Buntar, Kullu', price:'₹1,500/person', description:'White water rafting on the Beas river. 14km stretch of rapids. Safety gear and certified guides included.', phone:'+919876500092', whatsapp:'919876500092', icon:'🚣‍♂️', tags:['kullu','rafting','adventure'] },
  { id:'para-kullu', category:'paragliding', image:'https://images.unsplash.com/photo-1504280741564-f21aeea18bf7?w=1600&auto=format&fit=crop', name:'Dobhi Paragliding Kullu', area:'Dobhi, Kullu', price:'₹2,000–3,000/flight', description:'High-altitude tandem flights in the Kullu valley. Smooth thermals and breathtaking views of apple orchards.', phone:'+919876500093', whatsapp:'919876500093', icon:'🪂', tags:['kullu','dobhi','tandem'] },
  { id:'bike-kullu', category:'bikes', image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600&auto=format&fit=crop', name:'Valley Moto Rentals', area:'Dhalpur, Kullu', price:'₹1,000–2,000/day', description:'Royal Enfields and Scooters for exploring Kullu, Naggar, and Tirthan. Helmets included.', phone:'+919876500094', whatsapp:'919876500094', icon:'🏍️', tags:['kullu','enfield','dhalpur'] },
  { id:'home-kullu-luxury', category:'homestays', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&auto=format&fit=crop', name:'Raison Heritage Estate', area:'Raison, Kullu', price:'₹12,000/night', description:'Luxurious 100-year-old stone farmhouse situated among kiwi and apple orchards alongside the river Beas.', phone:'+919876500095', whatsapp:'919876500095', icon:'🏠', tags:['kullu','heritage','luxury'] },
  { id:'home-kullu-quiet', category:'homestays', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&auto=format&fit=crop', name:'Great Himalayan Forest Stay', area:'Gushaini, Kullu', price:'₹2,500/night', description:'Extremely quiet deep-nature stay near GHNP boundary. Organic meals, zero noise pollution, pure detox.', phone:'+919876500096', whatsapp:'919876500096', icon:'🌲', tags:['kullu','ghnp','quiet'] },
  { id:'bike-manali-1', category:'bikes', image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600&auto=format&fit=crop', name:'Himalayan Riders Manali', area:'Old Manali', price:'₹1,200–2,500/day', description:'Royal Enfield Himalayan, Classic 350, and Activa available. Helmets, saddle bags included. Multi-day discounts for Spiti circuit.', phone:'+919876500001', whatsapp:'919876500001', icon:'🏍️', tags:['manali','enfield','scooty'] },
  { id:'bike-manali-2', category:'bikes', image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600&auto=format&fit=crop', name:'Spiti Moto Rentals', area:'Mall Road, Manali', price:'₹1,500–3,000/day', description:'Adventure-ready bikes with toolkit, puncture kit, and bungee cords. GPS tracker included. Pickup/drop at bus stand.', phone:'+919876500002', whatsapp:'919876500002', icon:'🏍️', tags:['manali','spiti','adventure'] },
  { id:'bike-shimla-1', category:'bikes', image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600&auto=format&fit=crop', name:'Hill Riders Shimla', area:'Lakkar Bazaar, Shimla', price:'₹800–1,800/day', description:'Scooters and bikes for Shimla-Kufri-Narkanda circuit. Valid license required. Fuel not included.', phone:'+919876500003', whatsapp:'919876500003', icon:'🏍️', tags:['shimla','scooty','kufri'] },
  { id:'cab-chd-manali', category:'cabs', image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0be2?w=1600&auto=format&fit=crop', name:'Chandigarh → Manali', area:'Chandigarh Pickup', price:'₹4,500–6,000', description:'Sedan or SUV, AC, experienced hill drivers. 10-12 hour drive via Mandi or Bilaspur route. Pickup from airport/railway station.', phone:'+919876500004', whatsapp:'919876500004', icon:'🚖', tags:['chandigarh','manali','airport'] },
  { id:'cab-delhi-shimla', category:'cabs', image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0be2?w=1600&auto=format&fit=crop', name:'Delhi → Shimla', area:'Delhi NCR Pickup', price:'₹5,500–7,500', description:'Innova, Ertiga, or Sedan. Experienced pahadi drivers who know every hairpin. Overnight halt option available.', phone:'+919876500005', whatsapp:'919876500005', icon:'🚖', tags:['delhi','shimla','intercity'] },
  { id:'cab-manali-kaza', category:'cabs', image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0be2?w=1600&auto=format&fit=crop', name:'Manali → Kaza (Spiti)', area:'Manali', price:'₹7,000–9,000', description:'SUV only — Atal Tunnel route via Kunzum Pass. 10-12 hours. Driver stays in Spiti for return trip. Fuel and tolls included.', phone:'+919876500006', whatsapp:'919876500006', icon:'🚖', tags:['manali','spiti','kaza','suv'] },
  { id:'tempo-manali', category:'tempo', image:'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop', name:'Tempo Traveller Manali', area:'Manali & Kullu', price:'₹12,000–18,000/day', description:'12-seater and 17-seater AC tempo travellers for group trips. Ideal for Rohtang, Solang, Spiti circuit. Push-back seats, music system.', phone:'+919876500007', whatsapp:'919876500007', icon:'🚐', tags:['manali','group','family'] },
  { id:'tempo-shimla', category:'tempo', image:'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1600&auto=format&fit=crop', name:'Shimla Group Transport', area:'Shimla & Surrounds', price:'₹10,000–15,000/day', description:'AC tempo travellers for Shimla-Kufri-Chail-Narkanda circuit. Corporate and wedding group specialists.', phone:'+919876500008', whatsapp:'919876500008', icon:'🚐', tags:['shimla','corporate','group'] },
  { id:'home-spiti', category:'homestays', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&auto=format&fit=crop', name:'Tashi Homestay, Kibber', area:'Kibber, Spiti (4,270m)', price:'₹1,200–1,800/night', description:'Traditional Spitian mud-brick home at one of the highest villages. Authentic meals — thukpa, momos, butter tea. Stargazing from rooftop.', phone:'+919876500009', whatsapp:'919876500009', icon:'🏠', tags:['spiti','kibber','authentic'] },
  { id:'home-tirthan', category:'homestays', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&auto=format&fit=crop', name:'Raju\'s Riverside Stay', area:'Tirthan Valley, Kullu', price:'₹1,500–2,500/night', description:'Wooden cottage on Tirthan River banks. Home-cooked Himachali meals, trout fishing, GHNP treks arranged. Perfect for couples and families.', phone:'+919876500010', whatsapp:'919876500010', icon:'🏠', tags:['tirthan','riverside','family'] },
  { id:'home-jibhi', category:'homestays', image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1600&auto=format&fit=crop', name:'Pine View Cottage Jibhi', area:'Jibhi, Banjar', price:'₹1,000–2,000/night', description:'Cozy wooden cottage surrounded by pine and deodar forest. Bonfire, local food, waterfall treks. Off-grid and peaceful.', phone:'+919876500011', whatsapp:'919876500011', icon:'🏠', tags:['jibhi','offbeat','nature'] },
  { id:'trek-op-1', category:'treks', image:'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600&auto=format&fit=crop', name:'Summit Himalayas', area:'Manali Base', price:'₹2,500–4,000/day', description:'ATOAI-certified trek operator. Hampta Pass, Bhrigu Lake, Beas Kund, Pin Parvati. All-inclusive — tents, meals, guide, permits.', phone:'+919876500012', whatsapp:'919876500012', icon:'🥾', tags:['manali','hampta','certified'] },
  { id:'trek-op-2', category:'treks', image:'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600&auto=format&fit=crop', name:'Parvati Valley Treks', area:'Kasol Base', price:'₹1,500–3,000/day', description:'Local guides for Kheerganga, Rasol, Grahan, and Chalal. Small group sizes (max 8). Camping gear provided.', phone:'+919876500013', whatsapp:'919876500013', icon:'🥾', tags:['kasol','kheerganga','budget'] },
  { id:'trek-op-3', category:'treks', image:'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600&auto=format&fit=crop', name:'Dharamshala Trek Co.', area:'McLeodGanj', price:'₹2,000–3,500/day', description:'Triund, Indrahar Pass, and Kareri Lake specialists. Forest permits handled. Snow trek options Dec-Feb.', phone:'+919876500014', whatsapp:'919876500014', icon:'🥾', tags:['dharamshala','triund','snow'] },
  // DHARAMSHALA SPECIFIC SERVICES
  { id:'mini-ride-dharamshala', category:'bikes', image:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=1600&auto=format&fit=crop', name:'Mini Ride — Bike & Scooty Rental', area:'Kotwali Road, Sudher, Dharamshala', price:'₹500–1,200/day', description:'Verified local bike and scooty rental on Kotwali Road opposite IDBI Bank in Sudher. Activa, Pleasure, and Royal Enfield available. Short-term and multi-day rentals for McLeodGanj, Triund base, Bir Billing, and Kangra circuit. Helmets included.', phone:'', whatsapp:'', icon:'🏍️', tags:['dharamshala','mcleodganj','scooty','enfield','verified'], mapsLink:'https://maps.app.goo.gl/bJ9yFEnELM1hKKd56' },
  { id:'para-bir', category:'paragliding', image:'https://images.unsplash.com/photo-1504280741564-f21aeea18bf7?w=1600&auto=format&fit=crop', name:'Billing Paragliding Club', area:'Bir Billing, Kangra', price:'₹2,500–3,500/flight', description:'Tandem paragliding from Billing (2,430m) with certified pilots. 15-25 min flight. GoPro video included. World Cup venue.', phone:'+919876500015', whatsapp:'919876500015', icon:'🪂', tags:['bir','tandem','gopro'] },
  { id:'para-solang', category:'paragliding', image:'https://images.unsplash.com/photo-1504280741564-f21aeea18bf7?w=1600&auto=format&fit=crop', name:'Solang Sky Sports', area:'Solang Valley, Manali', price:'₹1,500–2,500/flight', description:'Short tandem flights over Solang Valley. Combo packages with zorbing, ATV ride available. Seasonal (Mar-Nov).', phone:'+919876500016', whatsapp:'919876500016', icon:'🪂', tags:['manali','solang','combo'] }
];
